version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    command: gunicorn sinel_web.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/home/sinel_web/app/static
      - assets_volume:/home/sinel_web/app/assets
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/sinel_web/app/static
      - assets_volume:/home/sinel_web/app/assets
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: null
  static_volume: null
  assets_volume: null
